travis:
  secure:
    BINSTAR_TOKEN: PYazoLTE0g9eAkrs9flQnKTICndr9ADYBFRfT+ilTTKMsUSyd0Zaw6nSVlZFaT/bL0Bc+t1koTyA6PkxF2xCJMQSguO3609rTqpGL49FYjbUsHER+R6/ZBTgU+cr15/FO7FEt4FeeqXmimr3bKF71723ZXPIDqKd5d6ZwhQsDMPIbuAkerNtTRErFpkY4Lp933ABHHQ+cBUbQWQwFrl2YGvFjXPh/zcpq+fZOxWHhJDlfH5MIiV3LUom9GykhbTkNhbbcFiyYHdZVT4rnzWLPGqTSD/RWeKrn39WxnrqMEIlbCSLO0sINSy0b+sEvt8th1t5lXlyRazhXS/sO/hecJ7b5fjx0K9aVhyos3K5HrQRus8kEklWCsk2gMZHfvtwl2Epw3lrxRqOYo6wOS/pmbH7tnlBe05VDBD4mlN4G7VUvcyvldFi2MLJgLiCaan0LJt9sU2T2ZgJunv2B6UisNTAAtd1pQSEX64Z5nQQyPEuazeb/Gt0q625RlSMrSJ1i99/PczPYPcbzbk4PYCss1uFv/ArA3dOIt05oa3oeuXDsU7/pbkvX7BL43lpkfSfFwTGO6S/PzUXdwI51N4UEl7wATBn0Fhv5Fm5K8VGNbCRYb8m6hUk7ttXPqf8/Gq0bfw5PtB6Gi54Eh/nkbFwXJGuCIM6Qkzb8S21ACKTxXc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
